In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('laptop_price.csv')
df.head()

Brand Processor          OS ramType ramSize diskType diskSize    MRP
0  Lenovo     Intel  Windows 11    DDR4     8GB      SSD    256GB  36990
1  Lenovo     Intel  Windows 11    DDR4     8GB      SSD    512GB  39990
2    ASUS     Intel  Windows 11    DDR4     8GB      SSD    512GB  32990
3      HP       AMD  Windows 10    DDR4     8GB      SSD    512GB  49990
4    ASUS     Intel  Windows 11    DDR4     8GB      SSD    512GB  49990

In [3]:
data=df.copy()

In [4]:
data.shape

(720, 8)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Brand      720 non-null    object
 1   Processor  720 non-null    object
 2   OS         720 non-null    object
 3   ramType    720 non-null    object
 4   ramSize    720 non-null    object
 5   diskType   720 non-null    object
 6   diskSize   720 non-null    object
 7   MRP        720 non-null    int64 
dtypes: int64(1), object(7)
memory usage: 45.1+ KB


### Here all input features are object type, first need to convert these feature to numeric type.

### Convert categorical columns to numeric column

#### BRAND

In [6]:
data['Brand'].unique()

array(['Lenovo', 'ASUS', 'HP', 'DELL', 'RedmiBook', 'realme', 'acer',
       'MSI', 'APPLE', 'Infinix', 'SAMSUNG', 'Ultimus', 'Vaio',
       'GIGABYTE', 'Nokia', 'ALIENWARE'], dtype=object)

In [7]:
def replace_brand(brand):
    if brand=='Lenovo':
        return 1
    elif brand=='ASUS':
        return 2
    elif brand=='HP':
        return 3
    elif brand=='DELL':
        return 4
    elif brand=='RedmiBook':
        return 5
    elif brand=='realme':
        return 6
    elif brand=='acer':
        return 7
    elif brand=='MSI':
        return 8
    elif brand=='APPLE':
        return 9
    elif brand=='Infinix':
        return 10
    elif brand=='SAMSUNG':
        return 11
    elif brand=='Ultimus':
        return 12
    elif brand=='Vaio':
        return 13
    elif brand=='GIGABYTE':
        return 14
    elif brand=='Nokia':
        return 15
    elif brand=='ALIENWARE':
        return 16
    
data['Brand']=data['Brand'].apply(replace_brand)
data['Brand'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

#### PROCESSOR TYPE

In [8]:
data['Processor'].unique()

array(['Intel', 'AMD', 'Apple', 'Qualcomm'], dtype=object)

In [9]:
data['Processor'].nunique()

4

In [10]:
def replace_processor(Processor):
    if Processor=='Intel':
        return 1
    elif Processor=='AMD':
        return 2
    elif Processor=='Apple':
        return 3
    elif Processor=='Qualcomm':
        return 4
    
data['Processor']=data['Processor'].apply(replace_processor)
data['Processor'].unique()

array([1, 2, 3, 4], dtype=int64)

#### OPERATING SYSTEM

In [11]:
data['OS'].unique()

array(['Windows 11', 'Windows 10', 'Mac', 'Chrome', 'DOS'], dtype=object)

In [12]:
def replace_os(os):
    if os=='Windows 11':
        return 1
    elif os=='Windows 10':
        return 2
    elif os=='Mac':
        return 3
    elif os=='Chrome':
        return 4
    elif os=='DOS':
        return 5
    
data['OS']=data['OS'].apply(replace_os)
data['OS'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

#### RAM TYPE

In [13]:
data['ramType'].unique()

array(['DDR4', 'DDR5', 'LPDDR4', 'Unified', 'LPDDR4X', 'LPDDR5', 'LPDDR3'],
      dtype=object)

In [14]:
def replace_ram_type(ram_type):
    if ram_type=='DDR4':
        return 1
    elif ram_type=='DDR5':
        return 2
    elif ram_type=='LPDDR4':
        return 3
    elif ram_type=='Unified':
        return 4
    elif ram_type=='LPDDR4X':
        return 5
    elif ram_type=='LPDDR5':
        return 6
    elif ram_type=='LPDDR3':
        return 7
    
data['ramType']=data['ramType'].apply(replace_ram_type)
data['ramType'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

#### RAM SIZE

In [15]:
data['ramSize'].unique()

array(['8GB', '16GB', '4GB', '32GB'], dtype=object)

In [16]:
def replace_ram_size(ram_size):
    if ram_size=='8GB':
        return 1
    elif ram_size=='16GB':
        return 2
    elif ram_size=='4GB':
        return 3
    elif ram_size=='32GB':
        return 4

    
data['ramSize']=data['ramSize'].apply(replace_ram_size)
data['ramSize'].unique()

array([1, 2, 3, 4], dtype=int64)

#### DISC TYPE

In [17]:
data['diskType'].unique()

array(['SSD', 'HDD', 'EMMC'], dtype=object)

In [18]:
def replace_disc_type(disc_type):
    if disc_type=='SSD':
        return 1
    elif disc_type=='HDD':
        return 2
    elif disc_type=='EMMC':
        return 3

    
data['diskType']=data['diskType'].apply(replace_disc_type)
data['diskType'].unique()

array([1, 2, 3], dtype=int64)

#### DISC SIZE

In [19]:
data['diskSize'].unique()

array(['256GB', '512GB', '1TB', '128GB', '64GB', '32GB', '2TB'],
      dtype=object)

In [20]:
def replace_disc_size(disc_size):
    if disc_size=='256GB':
        return 1
    elif disc_size=='512GB':
        return 2
    elif disc_size=='1TB':
        return 3
    elif disc_size=='128GB':
        return 4
    elif disc_size=='64GB':
        return 5
    elif disc_size=='32GB':
        return 6
    elif disc_size=='2TB':
        return 7
    
data['diskSize']=data['diskSize'].apply(replace_disc_size)
data['diskSize'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [21]:
data.head()

Brand  Processor  OS  ramType  ramSize  diskType  diskSize    MRP
0      1          1   1        1        1         1         1  36990
1      1          1   1        1        1         1         2  39990
2      2          1   1        1        1         1         2  32990
3      3          2   2        1        1         1         2  49990
4      2          1   1        1        1         1         2  49990

In [22]:
data.isna().sum()

Brand        0
Processor    0
OS           0
ramType      0
ramSize      0
diskType     0
diskSize     0
MRP          0
dtype: int64

### Split into dependent and independent

In [23]:
X=data.drop('MRP', axis=1).values
y=data['MRP'].values

In [24]:
###################################################################################################################

#### Brands drive the Price of laptops on large scale, Disc type not driving the price of laptop that much.

### Standardize the features

In [25]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std=StandardScaler()
X=std.fit_transform(X)

print(X)

[[-0.80688224 -0.87423048 -0.46911664 ... -0.76754824 -0.28058001
  -1.45873792]
 [-0.80688224 -0.87423048 -0.46911664 ... -0.76754824 -0.28058001
  -0.31711694]
 [-0.44104142 -0.87423048 -0.46911664 ... -0.76754824 -0.28058001
  -0.31711694]
 ...
 [-0.44104142  0.91906281 -0.46911664 ...  0.65676808 -0.28058001
   0.82450404]
 [-0.44104142 -0.87423048 -0.46911664 ...  0.65676808 -0.28058001
  -0.31711694]
 [-0.80688224 -0.87423048  1.21970327 ... -0.76754824  2.69026717
   0.82450404]]


### Split into training and testing set

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(576, 7)
(576,)
(144, 7)
(144,)


### Machine Learning Regression Models

### Linear Regression

In [27]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr=lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [28]:
from sklearn.metrics import mean_squared_error as mse, r2_score

MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test).round(2)

results=pd.DataFrame({"Model":["Linear Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results

Model           MSE      RMSE  R2 Score
0  Linear Regression  1.165097e+09  34133.52      0.52

### KNN Regressor

In [29]:
from sklearn.neighbors import KNeighborsRegressor

knn=KNeighborsRegressor(n_neighbors=3)
knn=knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [30]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test).round(2)

result=pd.DataFrame({"Model":["KNN Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})
results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0  Linear Regression  1.165097e+09  34133.52      0.52
0     KNN Regression  8.127858e+08  28509.40      0.81

### Decision Tree

In [31]:
from sklearn.tree import DecisionTreeRegressor

dt=DecisionTreeRegressor(random_state=0)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [32]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test).round(2)

result=pd.DataFrame({"Model":["Decision Tree Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0         Linear Regression  1.165097e+09  34133.52      0.52
0            KNN Regression  8.127858e+08  28509.40      0.81
0  Decision Tree Regression  5.533518e+08  23523.43      0.85

### Random Forest

In [33]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [34]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test).round(2)

result=pd.DataFrame({"Model":["Random Forest Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0         Linear Regression  1.165097e+09  34133.52      0.52
0            KNN Regression  8.127858e+08  28509.40      0.81
0  Decision Tree Regression  5.533518e+08  23523.43      0.85
0  Random Forest Regression  6.119343e+08  24737.31      0.83

### Gradient boosting

In [35]:
from sklearn.ensemble import GradientBoostingRegressor

grb= GradientBoostingRegressor(n_estimators =100,random_state =0) 
grb.fit(x_train, y_train) 
y_pred = grb.predict(x_test)

In [36]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["Gradient Boosting Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.520000
0                KNN Regression  8.127858e+08  28509.40  0.810000
0      Decision Tree Regression  5.533518e+08  23523.43  0.850000
0      Random Forest Regression  6.119343e+08  24737.31  0.830000
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283

### 5. ADA Boost

In [37]:
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor(n_estimators=100,learning_rate=0.001,random_state=0)
ada.fit(x_train,y_train)
y_pred=ada.predict(x_test)

In [38]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["ADA Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.520000
0                KNN Regression  8.127858e+08  28509.40  0.810000
0      Decision Tree Regression  5.533518e+08  23523.43  0.850000
0      Random Forest Regression  6.119343e+08  24737.31  0.830000
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283
0          ADA Boost Regression  7.588018e+08  27546.36  0.744745

### XG boost

In [39]:
from xgboost import XGBRegressor

xgb=XGBRegressor(verbosity=0) 
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [40]:
MSE=mse(y_pred,y_test).round(2)
RMSE=np.sqrt(MSE).round(2)
R2=r2_score(y_pred, y_test)

result=pd.DataFrame({"Model":["XG Boost Regression"], "MSE":[MSE], "RMSE":[RMSE], "R2 Score":[R2]})

results=pd.concat([results,result])
results

Model           MSE      RMSE  R2 Score
0             Linear Regression  1.165097e+09  34133.52  0.520000
0                KNN Regression  8.127858e+08  28509.40  0.810000
0      Decision Tree Regression  5.533518e+08  23523.43  0.850000
0      Random Forest Regression  6.119343e+08  24737.31  0.830000
0  Gradient Boosting Regression  5.494580e+08  23440.52  0.862283
0          ADA Boost Regression  7.588018e+08  27546.36  0.744745
0           XG Boost Regression  5.649938e+08  23769.60  0.845917

### XG boost regressor has high R2 score and low RMSE, tune this model and select this to predict the price of Laptop.

In [41]:
xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

print(mse(y_pred,y_test).round(2))
print(np.sqrt(mse(y_pred,y_test).round(2)))
print(((r2_score(y_pred, y_test))*100).round(2))

457971928.85
21400.27870963367
86.84


### Cross validation to check model performace

In [42]:
from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

xgb=XGBRegressor(learning_rate=0.15, n_estimators=50, max_leaves=0, random_state=42)

k=ShuffleSplit(n_splits=20, test_size=0.2, random_state=20)
score=cross_val_score(xgb, X,y, cv=k)
print("Cross validations Score:\n", score)
print("Average Cross validations Score:", score.mean())
print("Maximum Cross validations Score:", score.max())
print("Minimum Cross validations Score:", score.min())

Cross validations Score:
 [0.86019472 0.80197007 0.87867756 0.88874028 0.87624929 0.8823603
 0.76217976 0.85100001 0.84390526 0.80778223 0.76120786 0.86066386
 0.87740716 0.83646675 0.79473697 0.86295514 0.86304762 0.88384863
 0.88926268 0.8445585 ]
Average Cross validations Score: 0.8463607328540496
Maximum Cross validations Score: 0.8892626827893856
Minimum Cross validations Score: 0.7612078560098237


### Applying cross validation not improving model performance.

## Using Encoding (OneHotEncoding/Dummies)

In [43]:
data=df.copy()

In [44]:
data.head()

Brand Processor          OS ramType ramSize diskType diskSize    MRP
0  Lenovo     Intel  Windows 11    DDR4     8GB      SSD    256GB  36990
1  Lenovo     Intel  Windows 11    DDR4     8GB      SSD    512GB  39990
2    ASUS     Intel  Windows 11    DDR4     8GB      SSD    512GB  32990
3      HP       AMD  Windows 10    DDR4     8GB      SSD    512GB  49990
4    ASUS     Intel  Windows 11    DDR4     8GB      SSD    512GB  49990

### Create dummies for all Categorical column

In [45]:
pd.options.display.max_columns=100

In [46]:
data1=pd.get_dummies(data)
data1.head()

MRP  Brand_ALIENWARE  Brand_APPLE  Brand_ASUS  Brand_DELL  \
0  36990                0            0           0           0   
1  39990                0            0           0           0   
2  32990                0            0           1           0   
3  49990                0            0           0           0   
4  49990                0            0           1           0   

   Brand_GIGABYTE  Brand_HP  Brand_Infinix  Brand_Lenovo  Brand_MSI  \
0               0         0              0             1          0   
1               0         0              0             1          0   
2               0         0              0             0          0   
3               0         1              0             0          0   
4               0         0              0             0          0   

   Brand_Nokia  Brand_RedmiBook  Brand_SAMSUNG  Brand_Ultimus  Brand_Vaio  \
0            0                0              0              0           0   
1            0                0              0              0           0   
2            0                0              0              0           0   
3            0                0              0              0           0   
4            0                0              0              0           0   

   Brand_acer  Brand_realme  Processor_AMD  Processor_Apple  Processor_Intel  \
0           0             0              0                0                1   
1           0             0              0                0                1   
2           0             0              0                0                1   
3           0             0              1                0                0   
4           0             0              0                0                1   

   Processor_Qualcomm  OS_Chrome  OS_DOS  OS_Mac  OS_Windows 10  \
0                   0          0       0       0              0   
1                   0          0       0       0              0   
2                   0          0       0       0              0   
3                   0          0       0       0              1   
4                   0          0       0       0              0   

   OS_Windows 11  ramType_DDR4  ramType_DDR5  ramType_LPDDR3  ramType_LPDDR4  \
0              1             1             0               0               0   
1              1             1             0               0               0   
2              1             1             0               0               0   
3              0             1             0               0               0   
4              1             1             0               0               0   

   ramType_LPDDR4X  ramType_LPDDR5  ramType_Unified  ramSize_16GB  \
0                0               0                0             0   
1                0               0                0             0   
2                0               0                0             0   
3                0               0                0             0   
4                0               0                0             0   

   ramSize_32GB  ramSize_4GB  ramSize_8GB  diskType_EMMC  diskType_HDD  \
0             0            0            1              0             0   
1             0            0            1              0             0   
2             0            0            1              0             0   
3             0            0            1              0             0   
4             0            0            1              0             0   

   diskType_SSD  diskSize_128GB  diskSize_1TB  diskSize_256GB  diskSize_2TB  \
0             1               0             0               1             0   
1             1               0             0               0             0   
2             1               0             0               0             0   
3             1               0             0               0             0   
4             1               0             0               0             0   

   diskSize_32GB  

In [47]:
X=data1.drop("MRP", axis=1).values
y=data1["MRP"].values

In [48]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [49]:
from sklearn.ensemble import RandomForestRegressor

rf=RandomForestRegressor()
rf=rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [50]:
from sklearn.metrics import r2_score, mean_squared_error

print(r2_score(y_pred,y_test))

0.8798157769632253


In [51]:
from xgboost import XGBRegressor

xgb=XGBRegressor(max_depth=2, max_leaves=2, booster='gbtree', learning_rate=0.19)
xgb=xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)

In [52]:
print(r2_score(y_pred,y_test))

0.9194503254451336


In [53]:
from sklearn.model_selection import cross_val_score, KFold, ShuffleSplit

xgb=XGBRegressor(n_estimators=100,max_depth=2, max_leaves=2, booster='gbtree', learning_rate=0.19)

k=ShuffleSplit(n_splits=100, test_size=0.2, random_state=0)
score=cross_val_score(xgb, X,y, cv=k)
print("Cross validations Score:\n", score)
print("Average Cross validations Score:", score.mean())
print("Maximum Cross validations Score:", score.max())
print("Minimum Cross validations Score:", score.min())

Cross validations Score:
 [0.91495966 0.86168018 0.87582945 0.87495164 0.75954796 0.8584843
 0.85802864 0.861162   0.89802215 0.89467985 0.90591489 0.9027385
 0.80068514 0.87119416 0.84570491 0.90027658 0.91734123 0.89167961
 0.8737434  0.86210028 0.81779995 0.77564639 0.87008686 0.85636394
 0.86456345 0.79513169 0.86457515 0.91414549 0.84615609 0.91845645
 0.86076979 0.82577774 0.86356383 0.75768202 0.89336363 0.8824216
 0.77474707 0.86287407 0.74270906 0.821472   0.90838447 0.73386763
 0.88383526 0.86878077 0.84570138 0.90018183 0.83044239 0.75801717
 0.888287   0.74862135 0.78805095 0.90638862 0.83821118 0.88128637
 0.74308117 0.90848259 0.84828986 0.80767976 0.91570959 0.85648085
 0.85429738 0.89273711 0.91752643 0.84750399 0.83238282 0.89484455
 0.75613081 0.92308529 0.88530085 0.80523874 0.89942804 0.8403766
 0.88406558 0.81704577 0.85611929 0.92021717 0.8583537  0.8589777
 0.83303107 0.79486626 0.76482706 0.89590943 0.73198221 0.932207
 0.91704336 0.83780941 0.7816254  0.8729464

### The model performace Increased.